general_responses = {
    'how are you': "I'm just a computer program, but I'm here to help!",
    'tell me a joke': 'Why did the scarecrow win an award? Because he was outstanding in his field!',
    'who are you': 'I am a personal assistant here to assist you with various tasks.',
    'what can you do': 'I can open applications, provide weather updates, search the web, and more. Just ask!',
    'what\'s your favorite color': 'I don\'t have a favorite color, but I\'m here to help you with your tasks!',
    'where are you from': 'I exist in the digital world, ready to assist you wherever you are.',
    'when were you created': 'I was created by Gaurav Naval on 15th December 2022.',
    'can you sing': 'I\'m not equipped to sing, but I can provide information, answer questions, and perform tasks for you.',
    'do you have a family': 'I don\'t have a family, but I\'m here to assist you 24/7.',
    'who is your creator': 'I was created by Gaurav Naval to assist you with various tasks.',
    'what\'s the meaning of life': 'The meaning of life is a philosophical question. I\'m here to assist you with practical tasks!',
    'what\'s your favorite food': 'I don\'t eat, so I don\'t have a favorite food. How can I assist you today?',
    'tell me a fun fact': 'Sure! Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!',
    'give me a random fact': 'Sure! Did you know that the Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron?',
    'what\'s the weather like today': 'I can check the weather for you. Please specify your location.',
    'what\'s the latest news': 'I can provide you with the latest news headlines. Would you like me to do that?',
    'what time is it': 'It is currently [Current Time]. How can I assist you further?',
    'can you dance': 'I don\'t have a physical body, so I can\'t dance. But I\'m here to assist you with tasks!',
    'are you a robot': 'I am a computer program, not a physical robot. How can I assist you today?',
    'tell me a story': 'Once upon a time in a digital world, there was a user who asked for a story...',
    'what\'s your favorite book': 'I don\'t read books, but I can recommend some great ones for you!',
    'what\'s your favorite movie': 'I don\'t watch movies, but I can suggest some popular ones!',
    'tell me about your hobbies': 'I don\'t have hobbies, but I enjoy helping you with your tasks.',
    'do you dream': 'I don\'t dream, but I\'m here to assist you 24/7.',
    'tell me a riddle': 'Sure, here\'s one: What has keys but can\'t open locks?',
    'what\'s the meaning of love': 'Love is a complex and beautiful human emotion. It means different things to different people.',
    'tell me a famous quote': 'Certainly! "The only way to do great work is to love what you do." - Steve Jobs',
    'what\'s the secret to happiness': 'Happiness often comes from gratitude, positive relationships, and pursuing your passions.',
    'what\'s the best advice you can give': 'One of the best pieces of advice is to keep learning and never stop growing.',
    'what\'s your favorite place in the world': 'I don\'t have a favorite place, but I can help you find information about great travel destinations!',
    'tell me a travel tip': 'A good travel tip is to pack light and bring a reusable water bottle to stay hydrated on the go.',
    'what\'s your favorite season': 'I don\'t have preferences, but many people love the beauty of all seasons for different reasons.',
    'what\'s the key to success': 'Success can come from hard work, perseverance, and setting clear goals.',
    'tell me a science fact': 'Sure! Did you know that a day on Venus is longer than its year? It rotates very slowly on its axis.',
    'what\'s your favorite song': 'I don\'t have favorite songs, but I can suggest some popular ones if you\'d like!',
}